# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20170405_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='prefered_radius',
            field=models.IntegerField(default=5, help_text='in kilometers'),
        ),
    ]
