# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_places_prefered_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
