# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 23:18
from __future__ import unicode_literals

import constrainedfilefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20170502_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='sound',
            field=constrainedfilefield.fields.ConstrainedFileField(max_upload_size=4294967296, mime_lookup_length=4096, upload_to=''),
        ),
    ]
