# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 02:25
from __future__ import unicode_literals

import constrainedfilefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20170502_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='sound',
            field=constrainedfilefield.fields.ConstrainedFileField(max_upload_size=4194304, mime_lookup_length=4096, upload_to=''),
        ),
    ]
