# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20170503_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='sound',
            field=models.FileField(upload_to=''),
        ),
    ]
